# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('category_slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-название')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('post_slug', models.SlugField(max_length=200, verbose_name='URL-название')),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='blog_titels/', verbose_name='Миниатюра')),
                ('post_description', models.TextField(blank=True, verbose_name='Описание')),
                ('post_short_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Короткое описание')),
                ('post_available', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('post_posted', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'ordering': ['-id'],
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
    ]
